version: '3.3'

services:
  ba-logs-ui:
    image: dotersojet/shared_images:ba-logs-ui
    healthcheck:
      test: "curl -s -I -H \"Accept: application/json\"  http://localhost:3000/api/health | grep -q \"200 OK\" && echo \"Grafana health is OK\" || exit 1"
      interval: 1m
      timeout: 30s
      retries: 10
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      DEFAULT_USER_LOGIN: ${DEFAULT_USER_LOGIN}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}
      DOMAIN_NAME_FOR_UI: ${DOMAIN_NAME_FOR_UI}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.node_name.Elasticsearch == true]
    logging:
      driver: local
    ports:
      - target: 3000
        published: 3005
        protocol: tcp
        mode: ingress
