version: '3.3'

services:
  ba-logs-ui:
    image: dotersojet/shared_images:ba-logs-exporter
    healthcheck:
      test: "cd /app && perl processor_health_check.pl"
      interval: 1m
      timeout: 5s
      retries: 10
    environment:
      ES_NODES: ${ES_NODES}
      HOST_INSTANCE_LOGS_IP: ${HOST_INSTANCE_LOGS_IP}
      EXPORTER_PROCESSING_TIMEOUT_SEC: ${EXPORTER_PROCESSING_TIMEOUT_SEC}
    deploy:
      mode: global
      placement:
        constraints: [node.labels.node_name.PortaAdmin == true]
    logging:
      driver: local
    volumes:
      - type: bind
        source: /var/log/porta-admin
        target: /var/log/porta-admin

