version: '3.8'

services:
  ba-logs-es-supervisor:
    image: dotersojet/shared_images:ba-logs-es-supervisor
    healthcheck:
      test: "cd /app && perl processor_health_check.pl"
      interval: 1m
      timeout: 5s
      retries: 10
    environment:
      ES_NODES: ${ES_NODES}
      LOGS_CLEANUP_DAYS: ${LOGS_CLEANUP_DAYS}
      SUPERVISOR_PROCESSING_TIMEOUT_MIN: ${SUPERVISOR_PROCESSING_TIMEOUT_MIN}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.node_name.Elasticsearch == true]
        max_replicas_per_node: 1
    logging:
      driver: local
